### ISSUE TITLE
Add SSL/HTTPS

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#120]
Add an SSL certificate to enable HTTPs.

**Comment by Matoo125** [comment]
Zdá sa mi, že toto je celkom jednoduchý problém s prístupom do administrácie / na server. Ak to beží na App Engine, google by mal poskytovať certifikát automaticky, iba to bude treba niekde aktivovať. https://cloud.google.com/appengine/docs/standard/python/securing-custom-domains-with-ssl

Nastaviť vlastný certifikát by malo byť pár príkazov do commandline https://techmonger.github.io/46/free-ssl-google-cloud/

Dokonca existuje aj služba, ktorá vygeneruje SSL a ten už iba stačí nahrať na server https://www.sslforfree.com/

**Comment by hnykda** [comment]
Na app engine to neběží, máme to ve vm (dříve hlavně kvůli ceně, jelikož to bylo na free vps).
