### ISSUE TITLE
pulling the content of http://effectivethesis.com/theses/#disciplines from backup

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#127]
In http://effectivethesis.com/theses/#disciplines - Would it be possible to substitute the current content with a content that was there before we deployed the redesigned version (the old production)? In the previous version I had some notes which are not in the current version

**Comment by hnykda** [comment]
# Note for myself
https://gist.github.com/hnykda/db48ba33b50182d6fe6f246a57f3ad79

**Comment by zarybnicky** [comment]
@DavidJanku It this still relevant?

**Comment by DavidJanku** [comment]
Not anymore :)

Dne po 30. 11. 2020 10:37 uživatel Jakub Zárybnický <
notifications@github.com> napsal:
