### ISSUE TITLE
Newsletter button

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#128]
in the footnote, there is currently a hyperlinked sentence " Stay in touch and get our quarterly updates by signing up to our newsletter!" linking to http://eepurl.com/gAXAxX>

Can remove the hyperlink from the sentence and add a button "Sign up <linking to http://eepurl.com/gAXAxX> " below?

**Comment by rakyi** [comment]
Resolved in 37dbb594283cb1c6f30a828f15740eaaaaf543d9.
