### ISSUE TITLE
On mobile devices, navigation is hidden under logo

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#13]
![image](https://user-images.githubusercontent.com/2741256/34652246-fc231706-f3db-11e7-9a68-3b2ad76ed034.png)

**Comment by Daver2910** [comment]
This issue happens when screen is < 400px wide. Suggest putting logo text in <h3> and adding class to wrap text.

**Comment by hnykda** [comment]
Agree. By the way, when you write something on github, it uses [markdown](https://guides.github.com/features/mastering-markdown/). So your previous post is partly interpreted as HTML (specially that `<h3>` tag) :-)
