### ISSUE TITLE
Contact form doesn't work

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#130]
The contact form on the page http://effectivethesis.com/project/ doesn't work - when I try to send a message through, it redirects me to http://effectivethesis.com/theses/ask_us_anything/ and just message "Something went wrong when contacting us" appears and no email gets through.

Also, can I get a link specifically to the contact form? E.g. something like http://effectivethesis.com/project/#contact?

**Comment by rakyi** [comment]
I fixed the form in admin. We fixed some typos in code, but forgot to fix it also in page source in admin.

There is already this link available: http://effectivethesis.com/project/#ask-anything
Is that sufficient?

**Comment by hnykda** [comment]
@DavidJanku Has this been fixed then? Move it to `Done` please if yes.

**Comment by DavidJanku** [comment]
Thanks!
