### ISSUE TITLE
changes to homepage 

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#133]
This one is not necessary to be ready by tomorrow, but the earlier the better. 
This is how it should look like
![homepage1](https://user-images.githubusercontent.com/31438579/66272167-81975e80-e866-11e9-8da9-6fcbd7a37a4e.jpg)

----> the Undergraduate/masters; PhD would probably be collapsable headlines, including [this text](https://docs.google.com/document/d/12sQ9DmOtMCQpj4Vi2VhuJbjmKOLbWFzHHzf3Nv1yG7U/edit?usp=sharing). I'm open to other design solution, but the main point is to have this text included on the homepage and it shouldn't take too much space.

---> the two blocks below could look the same as Example topic areas blocks on the [current homepage](http://effectivethesis.com/) but the text would be above the pictures, not below. [This](https://www.pexels.com/photo/wood-light-creative-space-68562/) is the picture for the "Topics" block and this picture and headline Topics should be hyperlinked to http://effectivethesis.com/theses/. [This](https://www.pexels.com/photo/two-woman-chatting-1311518/) is the picture for the "Coaching" block and this picture and headline Coaching should be hyperlinked to http://effectivethesis.com/thesis-coaching/

**Comment by DavidJanku** [comment]
grafička ještě navrhuje toto řešení - 
![image](https://user-images.githubusercontent.com/31438579/66841830-8943bb00-ef6a-11e9-9d03-a59ac068fd7a.png)
a takto to vypadá když by to bylo otevřené-->
<img width="748" alt="Snímek obrazovky 2019-10-14 v 16 27 54 (1)" src="https://user-images.githubusercontent.com/31438579/66841888-9fea1200-ef6a-11e9-9622-687fbe88be49.png">

-- mě je asi jedno které z těch řešení zvolíme, zatím mezi tím nedokážu vidět zas takový rozdíl

**Comment by veselyvojtech** [comment]
@DavidJanku Hi, should we try to go in the direction of the second option?

One thing that is not clear to me is how the page should look like if only of the collapsible blocks is open. Should the other side be blank or should the other text block be open as well?

**Comment by DavidJanku** [comment]
@veselyvojtech good point! I haven't thought about it yet - in that case, the first version (vertical buttons) seems better.

**Comment by DavidJanku** [comment]
Great, it starts looking good! Few notes:

1) the buttons "Undergraduate/masters" and "PhDs" could be of normal size (not across the whole screen, but as long as to contain the Undergraduate/masters label), aligned to the center.

![image](https://user-images.githubusercontent.com/31438579/71542540-fd85dc00-2967-11ea-94ce-14b4b5b8b4d6.png)

2)  The text above the pictures "Topics" and "Coaching" should be more salient, e.g. the as salient as  the "who will benefit the most from this service..." text

3) the labels "Topics" and "Coaching" on the pictures should be bigger and more salient (at least twice as big as they are now)

![image](https://user-images.githubusercontent.com/31438579/71542576-60777300-2968-11ea-852f-4820bc18dbcf.png)

**Comment by DavidJanku** [comment]
Hi, 
couple more minor tweaks:

1) the labels of buttons Undergradutes/masters and PHDS should be changed to UNDERGRADUATE/MASTER and PHD

2) the part with the pictures should have headline, under that the picture and under that the text with the smaller font size - like this

![topics](https://user-images.githubusercontent.com/31438579/71885724-36c60500-313b-11ea-9270-108d99bef6d1.jpg)

3) there should be a larger space between "Check the finished theses of students we advised and what are current students working on" and "What they say about us" so it is more visually separated

4) the label of the button under the "Check the finished theses of students we advised and what are current students working on" should be "view more" instead of "finished"
