### ISSUE TITLE
Changes to the application form on the Topics page 

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#137]
I'd like to change the application form on the bottom of [this page](https://effectivethesis.com/theses/) accordingly:

- [ ] change the text in the 3rd field from "Would you be interested in anything listed above?..." to "Which ideas have you considered so far if any? Why these ideas specifically?"

- [ ] add another field to the bottom with a question "How did you find out about this website?"

**Comment by hnykda** [comment]
Done

![image](https://user-images.githubusercontent.com/2741256/68337721-65931100-00e1-11ea-92b3-f0fc66ee3b44.png)
