### ISSUE TITLE
secondary filtering in Topics

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#139]
Bylo by super přidat sekundární filtrování - poté, co člověk klikne na [Psychology](https://effectivethesis.com/theses/?discipline=psychology#disciplines), aby se mu nabídla možnost zvoli i podobor - ty jsou zatím udělané jen v textu k jednotlivým širším tématům (například #social psychology #industrial-organisational psychology). Ideálně když člověk klikne na  #social psychology tak by se mu měly vyfiltrovat jen témata co mají tento tag. 
Jakým způsobem se budou témata zobrazovat je asi jedno, ale měl by tam být vždy kompletní text toho daného tématu (tzn že kdyby to byly ty boxy jak jsme to měly dříve tak by ty boxy neměly mít standartní rozměr, ale měl by v nich být celý text čitelný rovnou, bez prokliku a otevírání nové stránky (např. jako [tohle](https://effectivethesis.com/mapping-forms-altruism/))

Mělo by to jinak fungovat i pro jiné disciplíny než jen pro Psychology. Jiné disciplíny budou mít jiné podobory (každá bude mít specifické podobory).  

Předpokládám že tam asi bude více věcí které si budeme muset vyjasnit, tak se prosím ptejte zde a já zkusím upřesnit co zvládnu.

**Comment by hnykda** [comment]
Nejsem si jistý, jestli to je z UI hlediska dobrý nápad. Zaprvé to je další burden na tebe to udržovat a za druhé mi to přijde jako další krok k tomu abych se dostal k čemu chci. Nechce prostě udělat další disciplíny typu `Psychology (social)` `Psychology (moral)` ... ? Nebo toho bude skutečně tolik?

Jak to zobrazovat úplně jedno není, souvisí s tím moje obavy - jak to udělat aby to vypadalo dobře a lidi to neodradilo.

**Comment by DavidJanku** [comment]
> Nejsem si jistý, jestli to je z UI hlediska dobrý nápad. Zaprvé to je další burden na tebe to udržovat a za druhé mi to přijde jako další krok k tomu abych se dostal k čemu chci. Nechce prostě udělat další disciplíny typu Psychology (social) Psychology (moral) ... ? Nebo toho bude skutečně tolik?

myslím že toho bude tolik

Jenom takový log- od kamaráda jsem dostal feedback že teď ta stránka [psychology](https://effectivethesis.com/theses/?discipline=psychology#disciplines) vypadá jako stěna textu a že by více ocenil kdyby tam byl u každého tématu třeba jen nadpis, ty sub-disciplíny a pak tlačítko "Read more" po kterém by se ten text vysunul (takže collapse?) - to by možná bylo i elegantnější a méně náročnější než filtrování podle subdisciplín.

Zatím bych ale tenhle issue neřešil, zkusím to otestovat ještě s pár lidma.

**Comment by hnykda** [comment]
Ok.

**Comment by DavidJanku** [comment]
EDIT: I don't think this makes sense anymore.

**Comment by hnykda** [comment]
OK, colsing.
