### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by janrvdolf** [ea-czech-republic/efektivnialtruismus.cz#159]
Hi, 

At [https://efektivni-altruismus.cz/about-us/](https://efektivni-altruismus.cz/about-us/), there is a broken link **_frequently asked questions_** in the text. In the URL is missing "efektivni-".

Have a nice day, Jan

**Comment by zarybnicky** [comment]
@hnykda @DavidJanku If I'm seeking this right, efektivni-altruismus.cz is still the name of this repository, but the actual webapp's source code is now elsewhere, right? (Looking at #101)

**Comment by hnykda** [comment]
Hey. Yeah, we should likely rename it to effective thesis... Should I do it?

**Comment by hnykda** [comment]
And thanks @janrvdolf . I will report it.

**Comment by hnykda** [comment]
Fixed
![image](https://user-images.githubusercontent.com/2741256/103822942-5b67fc00-5071-11eb-89b8-9962dc5ec357.png)
