### ISSUE TITLE
Center all content

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#17]
Vycentrovat ten obsah. v chromu na obrazovce 1366x768 je nalepný doleva

**Comment by hnykda** [comment]
![image](https://user-images.githubusercontent.com/2741256/30136967-7b8fe2d4-9361-11e7-8910-e8d752d645dc.png)

Takhle to vidím já v chromu na 1366x768 a přijde mi to jako ergonomické řešení (obecně se obsah doporučuje zarovnávat spíše doleva).

**Comment by hnykda** [comment]
@DavidJanku Je to takhle v pohodě tedy?

**Comment by hnykda** [comment]
https://github.com/ea-czech-republic/efektivnialtruismus.cz/pull/84
