### ISSUE TITLE
Priority 3 [theses] filtrovani temat

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#18]
Tenhle problem reportoval nejaky uzivatel. Zkousel jsem to a taky mi to nefunguje - resp. Funguje to kdyz clovek klikne na tlacitko "go back" primo na te strance ale nefunguje to pokud klikne "zpet" ve svem prohlizeci:
Filtrování dle oborů nefunguje, jak má - pokud zašktnu nějaký obor, rozkliknu podstránku popisu nějakého tématu z něj něj a pak se vrátím přes funkci prohlížeče "zpět", obor je sice stále zaškrtlý, ale ve výsledcích se to neprojeví (místo toho vidím všechna témata). Pokud v tuto chvíli navíc zašrktnu nějaké jiné téma a následně ho odškrtnu, zmizí mi všechny výsledky (zobrazí se 0 témat)

**Comment by hnykda** [comment]
fixed
