### ISSUE TITLE
Priority 1 (theses) web redesign - landing page

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#20]
Reace k Lubosove fotce:
Dal bych za to nejakou grafiku, nejakej obrazek treba nebo tak neco (bohuzel me zatim nenapada jaky obrazek nebo grafiku). Takto mi to prijde strasne hole. Dal bych tam dal hlavni napis "Find your thesis topic" a radek pod to nejak mene vyrazne "Make use of your work and effort", a radek pod to "make the world a better place". Vedle tlacitka "choose your topic" bych hodil jeste tlacitko "about project" ktere by odkazovalo na samostatnou stranku v menu kde by byly informace o projektu. Barvu tlacitka bych nechal na Danovi, aby to zapadalo do designu soucasneho webu.
---- obrazek zatim nemame vymysleny tak ze bys tam zatim bud zadny nedaval nebo pokud te napadne neco dobreho...
![lubos_navrh](https://user-images.githubusercontent.com/31438579/29998922-35b746b2-9037-11e7-86f4-45038704c775.png)

**Comment by hnykda** [comment]
Nebyl jsem schopný za to dát ten obrázek, zatím tam je prázdno.

**Comment by DavidJanku** [comment]
To prázdno vypadá dobře. Mě se takový jednoduchý design líbí, tak dokud nás nenapadne něco lepšího asi to nechme takto

**Comment by hnykda** [comment]
Souhlas, mně se to také líbí
