### ISSUE TITLE
Priority 1 (theses) editing tags

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#21]
tagy bych dal větším písmem a zarovnal je do sloupce spolu s tématy - takto jsou v užším sloupci a je tam vytvořený prázdný prostor
![2-9-2017_23-23-56](https://user-images.githubusercontent.com/31438579/29998891-9ff9c370-9036-11e7-8329-800f92c67126.jpg)

**Comment by hnykda** [comment]
hotovo, oboje má stejnou šířku (a raději tu menší)
