### ISSUE TITLE
(theses) Feedback button

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#24]
přidat na všechny stránky (Theses, Project, Propose, Contact) feedback button (viz přiložený obrázek) --- ten bude odkazovat na samostatnou stránku s formulářem s nepovinnými poli: "What would you like to tell us?" "Is there any fuctionality you miss on our website?" "Is there any information you miss?" "Do you have any other ideas how to improve our website?" 
![landing page 1](https://user-images.githubusercontent.com/31438579/30525655-815347ac-9c02-11e7-9ab1-8070635a9755.jpg)

---popřípadě tyto možnosti:
A) jestli ti ten můj návrh přijde hodně složitý, tak to můžeme udělat podle toho jak jsi navrhoval výše https://codepen.io/cjmosure/pen/WQQRjo - s tím, že by bylo dobré aby to tlačítko vyskočilo z horní lišty a ne ze spodní, jestli je to možné, taky by bylo dobré aby to tlačítko bylo nějak barevně zvýrazněné, třeba tou tmavě zelenou. Obsah těch formulářů můžeš navolit? 
B) pokud by to nešlo, tak bychom to mohli udělat i podle tvého druhého návrhu https://codepen.io/Dante_Kelly/pen/raYvNr -ten by byl možná ještě lepší, pokud by bylo možné upravit ten formulář (nepotřebujeme pole Jméno, pole email bych zvážil, ale prakticky taky není potřeba). Navíc by se k tomuto okénku vyskakujícímu z boku daly přidat (snad?) i odkazy na přímé sdílení na fb a na twitteru, jak to má na svých stránkách Luboš (vpravo) http://lubomirkoblasa.cz/
C) pokud by jakákoli z těchto variant byla pro tebe moc složitá, mohl bys tu práci přerozdělit třeba mezi Chrise a Bráchu, abychom to fakt do toho týdne stihli?

**Comment by DavidJanku** [comment]
Ahoj, vím že ti dalo dost práce a moc si toho vážím, ale v té patičce mi to nepřijde moc dobré. Jednak mi přijde že to vypadá docela neprofesionálně na rozdíl od zbytku stránek které vypadají dost dobře a tak to může kazit celkový dojem. Co se týče funkcionality tak tam šlo hlavně o to říct si přímo o ten feedback - když nám někdo vermomocí bude chtít svůj feedback poslat tak může použít kontaktní formulář, nemusí k tomu mít speciální formulář v patičce. Šlo spíš o to udělat tam to tlačítko vyskakovací na boku nebo nahoře (třeba jak jsi to navrhoval tady: https://codepen.io/Dante_Kelly/pen/raYvNr nebo tady: https://codepen.io/cjmosure/pen/WQQRjo), aby všem jasně dalo najevo, že o ten feedback stojíme. Funkcionalita formuláře v patičce mi přijde nahraditelná kontaktním formulářem. 

Navrhoval bych to prozatím hodit do původní verze bez feedback formuláře v patičce. Přinejhorším to můžeme začít propagovat i bez feedback tlačítka, ale přijde mi to škoda promarnit návštevu několika stovek/tisíc lidí (podobně jak když nás sdíleli 80k) od kterých bychom potenciálně mohli dostat zpětnou vazbu a nějaké návrhy na zlepšení. Na druhou stranu mám pocit že když nezačneme ty stránky šířit co nejdřív, můžeme propásnout čas, kdy si většina studentů vybírá své téma a pak ať se budem s propagací snažit sebevíc, moc velký dosah a efekt to mít nebude. Přemýšlím teď jak tyto dva pohledy vyrovnat a najít mezi nimi nějakou rovnováhu. Ty by sis na to znovu našel čas cca kdy? Vím, že toho máš teď hodně, tak na tebe nechci moc tlačit, spíš se ptám pro informaci.

**Comment by hnykda** [comment]
Jaký je teď stav s tímhle? To výše jsme řešili na slacku, stačilo refreshnout statické files na serveru.

**Comment by DavidJanku** [comment]
jj tohle je vyřešeno
