### ISSUE TITLE
(theses) Donate button

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#25]
na stránku Project dát tlačítko Donate které přesměruje na stránku Donate hned na konec prvního odstavce (Our Project) a pak úplně dolů, místo textové sekce Donate

**Comment by Daver2910** [comment]
![donate button](https://user-images.githubusercontent.com/31806168/34769421-0ef132b8-f5fe-11e7-81de-0b400a914cdc.PNG)

Something like this? Please let me know what position you would like it and I assume we keep the same button color as the rest of the site, unless you want to highlight it with red/orange or smth else.
