### ISSUE TITLE
(theses) zobrazeni landing page na mobilu

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#26]
stačí upravit nadpis "Find your thesis topic" - aby se na mobilu zobrazoval o trochu menší (dvě slova na řádek) + upravit ta tlačítka aby nebyly pod sebou ale opět byly menší a vedle sebe. Vše ostatní je ok.

https://css-tricks.com/viewport-sized-typography/
https://v4-alpha.getbootstrap.com/content/typography/#responsive-typography
https://stackoverflow.com/questions/14537611/bootstrap-responsive-text-size
https://github.com/twbs/bootstrap/issues/13451

**Comment by hnykda** [comment]
Did my best. Deployed.

**Comment by DavidJanku** [comment]
tohle bych prosil ještě upravit - docela se to teď rozhodilo - takhle to vypadá na pc
![23-9-2017_14-17-51](https://user-images.githubusercontent.com/31438579/30773538-7e1cbc28-a06a-11e7-974c-7f59e37305fc.jpg) (tlačítka jsou jinak veliká)

takhle to vypadá na mobilu 
![theses_mobile_landing page](https://user-images.githubusercontent.com/31438579/30773587-7e0580a2-a06b-11e7-9781-b93370796241.png) (příliš malý nadpis Find your thesis topic; tlačítka nejsou stejně veliká a jsou pod sebou, měly by být vedle sebe)

a takhle to vypadá na Ipadu 
![theses_ipad_landing page](https://user-images.githubusercontent.com/31438579/30773599-cdd62a14-a06b-11e7-8b1b-354d08d4c4ed.jpg) --- tohle je ideální (až na ten zlom po slově "organizations," což je způsobeno tím, že jsem tam natvrdo dal <br> - ale určitě existuje elegantnější řešení + další věc je že to není na středu a na Ipadu se to zarovnává doleva, takže na pravo je prázdná mezera, která nevypadá dobře - to je ale asi jiný problém)

Bylo by dobrý kdyby ses na to ještě podíval, pokud s tím nedokážeš nic udělat tak to prosím dej do původního stavu jak to bylo před touto úpravou

**Comment by hnykda** [comment]
Tak jsem se na to ještě zkusil znova podívat. Je to nahrdcoděný, takže ti to nepůjde upravovat v adminu. Přijde mi to teď o něco lepší. Co říkáš?

**Comment by DavidJanku** [comment]
Na PC je to hezký, na tabletu taky, ale na mobilu se mi to pořád zobrazuje takhle (model mobilu je z roku 2015 a velikost display 5"
![mobil_landing page](https://user-images.githubusercontent.com/31438579/30787230-05722bf6-a17c-11e7-9221-dabc4f390b79.png)

**Comment by hnykda** [comment]
Na mém mobilu to vypadá takhle, ale mám novější model:

![image](https://user-images.githubusercontent.com/2741256/30807994-8cc5626e-a1fc-11e7-950c-7a4063f656cb.png)

Dle google analytics je po odfiltrování našich zařízení přístup z mobilů někde u 20%, z toho jsou na prvním místě iphony a ipady, tudíž bych to pro těch zbylých 5% nechal být jako low-priority problém

**Comment by hnykda** [comment]
V Chrome je možnost si zobrazit stránku jako kdyby to bylo na jiném zařízení, můžeš to schválně vyzkoušet. Nenašel jsem žádný z jejich nabídky (kde jsou nejpoužívanější telefony), kde by se to zobrazovalo blbě

![image](https://user-images.githubusercontent.com/2741256/30808198-69c7d34a-a1fd-11e7-8f58-4834f0c68e7c.png)

**Comment by DavidJanku** [comment]
ok, makes sense, asi mám nějaký netradiční mobil. jinak ta funkce v chromu je super, kde přesně ji najdu?
