### ISSUE TITLE
(theses) info o organizacích

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#27]
problém "jak lidi informovat od jaké organizace téma pochází" - napadlo mne několik řešení:
A) místo loga organizace dát vedle názvu tématu její jméno (např. Support programs in reducing meat consumption/ Animal charity evaluator) --- potenicální problémy: bude to pro lidi pochopitelné? a bude to vypadat hezky? 
B) přidat hned pod název tématu (mezi název tématu a tagy) větu "This topic is provided by /jméno organizace, ideálně extrahované z Providerů - pokud to nepůjde tak to přepíšeme ručně, nevadí/. For more information visit their websites (s odkazem na jejich stránky).
---- pokud to bude moc dlouhé tak věta "For more information visit their website" tam být nemusí a místo toho to jméno organizace dáme jako Link na jejich stránky
---- pokud by se ti nepodařilo tuto větu vměstnat mezi název tématu a tagy, tak bych to dal nejspíš pod ty tagy, nebo klidně i jinam, ale ideálně někde do prvního odstavce (třeba úplně nakonec - to by ale nevypadlo tak dobře jako když by to bylo mezi nadpisem a tagama)

---nejlépe tedy řešení B

**Comment by hnykda** [comment]
Hotovo.

**Comment by DavidJanku** [comment]
teď tě asi nechápu, ale ještě by to chtělo úpravu:
pointou mělo být: tahle stránka (http://theses.efektivni-altruismus.cz/theses/) slouží jenom k ochutnávce témat, má uživatele jen navnadit a ukázat mu, co všechno je možné zkoumat - proto na této stránce stačí, když to bude stejně jak to bylo předtím - jen název tématu a logo (at s proklikem nebo bez). Když to téma uživatele zaujme, tak si rozhlikne stránku s konkrétním tématem a tady už chce dostat co nejvíc informací, o tom daném tématu - (když si třeba rozkliknun toto téma http://theses.efektivni-altruismus.cz/effect-investigation-meat-consumption/) - proto až tady je potřeba dát tu větu "This topic is provided by Czech Association of EA (logo)"

**Comment by hnykda** [comment]
Aha, to pak jo. Fixed.

**Comment by DavidJanku** [comment]
takhle je to super, díky
