### ISSUE TITLE
(theses) editing of topic page 

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#29]
1) na každé stránce s popisem konkrétního tématu se zobrazuje část "Topic requirements" kterou můžeš změnit jenom ty. bylo by dobré tam přidat za větu "Certain requirements may come from the organization who created the topic and who will consult your thesis with you." ještě větu "Find out more about the process here" s linkem na odstavec Process na této stránce http://theses.efektivni-altruismus.cz/project/

2) tu další větu která je v současnosti tučně bych změnil na "Do you want to work on this topic? Submit your interest! Do you have any comment, question or suggestion? Please use the discussion thread below!"

3) Změnit nadpis toho formuláře: místo "Contact us" tam dát "Submit your interest"

4) ten feature "Disqus" který je pod každým tématem je v češtině - dá se to předělat do angličtiny?

**Comment by hnykda** [comment]
1, 2, 3 hotovo. 

4. disqus se alespoň co vím customizuje dle přístupu - pokud na to půjde vietnamec z vietnamu, bude to ve vietnamštině. To nenastavujeme my, ale dělá si to disqus sám. Dle mého expected behaviour.

**Comment by DavidJanku** [comment]
k tomuhle ještě maličkost - dalo by se to udělat tak, aby ta věta "Find out more about the process here" s odkazovala přímo na odstavec Process? Mají to tak třeba tady https://foundational-research.org/open-research-questions/#International_cooperation

**Comment by hnykda** [comment]
Jo, tomu se říká kotvy (anchors). Už jsem to tam přidal (sice přes hack, ale je to tam)

**Comment by DavidJanku** [comment]
perfekt, díky
