### ISSUE TITLE
(theses) --Může počkat - řazení témat v admin rozhraní

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#30]
Seznam témat se nám rozrůstá a když chci nějaké téma v admin rozhraní upravit nebo najít, dělá mi docela problém najít to specifické téma jen na základě toho kdy bylo naposledy upravováno (protože to často nevím). Chtělo by to přidal nějaké kritéria řazení do admin rozhraní - nejlépe řadit podle providerů, popřípadě pokud to nepůjde tak podle abecedy.

**Comment by hnykda** [comment]
Řadit lze v adminovi dle abecedy kliknutím na title. 
![image](https://user-images.githubusercontent.com/2741256/30758231-c8129008-9fd1-11e7-97ac-2569e78076ef.png)

**Comment by DavidJanku** [comment]
ok, zatím to stačí
