### ISSUE TITLE
(theses) chybové hlášky jsou v češtině

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#33]
![26-9-2017_15-42-45](https://user-images.githubusercontent.com/31438579/30866529-69e21c76-a2d1-11e7-9ec6-72e5aff722a5.jpg)

Tak jeste edit:
ve chromu a ve firefoxu jsou v cestine, v safari jsou v anglictine

**Comment by hnykda** [comment]
Tohle je způsobeno nastavením prohlížeče uživatele. Já to mám například v AJ a zobrazuje se to v AJ (firefox i chrome). 

Tudíž "not-a-bug"? Když tak reopen pokud to bude replikováno u někoho z ciziny.

**Comment by DavidJanku** [comment]
supr. to bude asi takové obecné pravidlo že se jazyk řídí podle nastavení prohlížeče že? Budu na to myslet
