### ISSUE TITLE
(theses) změna domény

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#37]
Dostali jsme feedback že se lidem nelíbí, že je doména v čestině. Komentátor si myslí, že: "Many people people will be less likely to click on a link if the domain name is in a foreign language. They will also be less likely to be able to remember the name of the website if they want to be able to visit it later."
Doménu thesis.efektivni-altruismus.cz jsme si drželi protože jsme na ni měli google adwords grant na 10 000 dolarů/měsíc, ale teď nám google povolil tento grant používat i na doménu effectivethesis.com, takže nám nic nebrání obsah přesunout.

+ ještě by bylo fajn mít koupenou i doménu effectivethesis.org

**Comment by hnykda** [comment]
done
