### ISSUE TITLE
(theses) přidat socials

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#38]
přidat k tlačítku Feedback i odkazy na přímé sdílení na fb a na twitteru, jak to má na svých stránkách Luboš (vpravo) http://lubomirkoblasa.cz/

**Comment by hnykda** [comment]
https://github.com/ea-czech-republic/efektivnialtruismus.cz/commit/7f7f998d5dc0e45e59ddbb332fdab579341b5cef

**Comment by DavidJanku** [comment]
![tablet1](https://user-images.githubusercontent.com/31438579/32985213-8f439e94-ccad-11e7-98a9-e7f9e608841d.jpg)
![tablet2](https://user-images.githubusercontent.com/31438579/32985214-901f5fc4-ccad-11e7-8801-8049c6a3f0f1.jpg)

**Comment by hnykda** [comment]
Co teď? Přidal jsem škálování a hodil to do prava.

**Comment by DavidJanku** [comment]
Co myslis tim skalovanim? Ted se to na tabletu zobrazuje jako hodne male. Slo by aby to vypadalo stejne jako predtim akorat to bylo vpravo? Na PC to funguje krasne a na mobilu nevim protoze muj Mobil neni typicky a na netu jsem nenasel zadny dobry program ktery by mi ukazal jak se to na mobilu zobrazuje
![17908a8a-924d-4bd5-9618-019ac5543f9c](https://user-images.githubusercontent.com/31438579/32991151-ef08854e-cd2d-11e7-835f-7e15bd4aa443.png)

**Comment by hnykda** [comment]
škálováním myslím to, že se to zmenší relativně podle okolních elementů na stránce (proto se to zmenší). Přijde ti, že se na to nedá trefit nebo že to člověk přehlídne/nepřečte? Já bych řekl, že ne, ale to je asi dost věc v kusu, nechám to na tobě.

Můžu to vrátit víceméně do předchozí varianty.

Jak to vypadá na různých zařízeních jde testovat přímo v prohlížeči jedním tlačítkem ve vývojářském módu: https://developers.google.com/web/tools/chrome-devtools/device-mode/

**Comment by DavidJanku** [comment]
Přijde mi obojí - že to člověk přehlídne i že se to nedá trefit. Vrátil bych to do původní varianty a pokud by to šlo tak to dát na pravou stranu (lidi čtou zleva do prava a na tabletech by jim to vlevo mohlo vadit)

**Comment by hnykda** [comment]
No, já to teď zkoušel na mém telefonu (ještě menší než tablet), a přišlo mi, že to furt bylo docela dobře funkční (trefil jsem všechny tlačítka co jsem chtěl a zároveň mi to nebralo moc místa). Vážně to chceš zrušit?

**Comment by hnykda** [comment]
gg

**Comment by DavidJanku** [comment]
Tak na mobilu ty social buttony klidne muzeme nechat, tam na tom podle me tolik ani nezalezi, protoze kdyz je to az vespod stranky tak se k tomu vetsina lidi asi nedostane. Ale na tabletu bych to nechal tak jak to bylo akorat vpravo (aby ta tlacitka byla velka). To o cem jsem na slacku uvazoval jestli na mobilu nezrusit bylo tlacitko Give us feedback. Ale nejsem si tim jeste uplne jisty, poradim se s nejakym webarem a dam vedet

**Comment by DavidJanku** [comment]
ještě připomínám tento issue . je to myslím zatím jediný problém co máme v responsivitě - na tabletu ta tlačítka nevypadají dobře když jsou shromážděná do skupiny 5 malých koleček u sebe a na mobilu je tento feature v podstatě zbytečný protože se k němu nikdo nedostane -museli bychom to na mobilu vymyslet jinak, ale to má teď velmi nízkou prioritu, takže bych řekl - spravit to na tabletu a nechat ten problém otevřený (nebo někde  v záloze)
