### ISSUE TITLE
(theses) upravit tagy

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#39]
ve feedbacku jsme dostali otázku, jestli by šlo tagy upravit aby tam nebyla ta čára dole --- tedy aby to nebylo jak teď "public_health" ale aby to bylo normálně "public health"

--- pokud by tohle bylo nějak složitý tak se na to vykašlete, je to fakt jen detail a v nějakém časovém horizontu (několika měsíců) zřejmě budeme měnit celý filtrovací systém.

**Comment by hnykda** [comment]
Na betě je tohle už možné přímo v adminovi pod http://beta.efektivni-altruismus.cz/admin/snippets/theses/tag/ . Akorát se člověk musí proklikat skrz všechny existující tagy třeba i k obrázkům atp. Ale je to nejčistší řešení a nemělo by zabrat déle než pár minu.
