### ISSUE TITLE
(theses) úprava textů

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#40]
úprava textů, ke kterým se z admin přístupu nedostanu:

Landing page:
button přejmenovat: "About our project"
Větu pod buttonem upravit: "Our organisations are selected based on the principles of Effective Altruism"

Individual topic pages
        - "Why we think it is important?" -> "Why do we think this is important?" or "Why we think this is important."
        - "Submit your interest" -> "Register your interest"
        - "any comment, question, suggestion" -> "any comments, questions, suggestions"
        - "Czech Association of EA" -> "Czech Association of Effective Altruism"
        - "be in a very high quality" -> "be very high quality" or "be of a very high quality"
        - "consult your thesis" -> "consult on your thesis"

**Comment by hnykda** [comment]
https://github.com/ea-czech-republic/efektivnialtruismus.cz/pull/46
https://github.com/ea-czech-republic/efektivnialtruismus.cz/pull/47

Problém s `"Czech Association of EA" -> "Czech Association of Effective Altruism"` je změnitelný v [adminovi](http://efektivni-altruismus.cz/admin/snippets/theses/thesisprovider/) - vytvořil to někdo z moderátorů thesis a jde to tam změnit.
