### ISSUE TITLE
(theses) komentovací feature je v češtině

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#41]
tím featurem myslím Discuss. Ověřil jsem to i přes lidi žijící v anglii, zobrazuje se jim to taky v češtině. Navrhuji nastavit jako defaultní jazyk AJ

**Comment by hnykda** [comment]
Nastaveno. Zkoušel jsem to a zdá se, že to pomohlo. Ale raději to vyzkoušet prosím.
