### ISSUE TITLE
(theses) zobrazování témat

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#48]
Dneska jsem konzultoval stránky se spolužačkou která se profesionálně věnovala web developmentu několik let a měla několik zajímavých postřehů. Tady je jeden, který by mohl být příčinou docela velkého procenta feedbacků které dostáváme:

Když člověk klikne na "Topics", zobrazí se mu odstavce Pick your study discipline a rovnou i Available theses. Co se domníváme že se stane u mnoha uživatelů (minimálně se to stalo té spolužačce + ještě jedné další kamarádce) je, že si lidé nevyberou žádnou study discipline a rovnou začnou scrolovat a pročítat témata. Vzhledem k tomu že ta témata jsou řazena náhodně tak je jen velmi malá šance že narazí na něco relevantního a možná stránky opustí s tím že to nění o ničem. 

Proto by bylo fajn nezobrazovat žádná témata dokud člověk nevybere "Study discipline". Šlo by to?

**Comment by hnykda** [comment]
https://github.com/ea-czech-republic/efektivnialtruismus.cz/commit/8c9d98d7d3759ed77d88215cf38b3dfb26a37905
