### ISSUE TITLE
(theses) Velikost témat

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#49]
Domnívám se (po konzultaci s několika lidmi co se věnují web developmentu), že v současném designu si lidé přečtou maximálně 3 první téma které jim (náhodně) přiřadíme a víc už nečtou, pokud je nějaké z těch prvních 3 nezaujalo. S tím se můžeme vyrovnat dvěma způsoby: 
1) Buď to můžeme považovat za fakt a zkusit lidem nabídnout témata, co pro ně budou co nejvíce relevantní (např. přidáním dalších filtrů), nebo 
2) můžeme změnit design témat tak, aby si lidé přečetli více než 3 témata - například udělat ty boxy menší, odstranit  z nich část "Why the topic is imporant" a zkrátit text popisu tématu ze 3 řádků třeba jen na jeden, můžeme také dát dvě témata vedle sebe, v jednu chvíli tedy uživatel uvidí 2x2 témata

Tohle zatím nechávám jako poznámku na okraj, se kterou zatím nemusíme pracovat, ale zřejmě bude dobré zkombinovat obě varianty až budeme dělat ten větší redesign

**Comment by hnykda** [comment]
The decision is here https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/58 , so closing this as duplicate.
