### ISSUE TITLE
Choosing a topic

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#54]
https://cacoo.com/diagrams/t0dRXcF8boiE4Hug#D101A
![image](https://user-images.githubusercontent.com/2741256/36078855-4af999fc-0f7c-11e8-962e-55712b4566d3.png)

- [x] 3 streamfields, in a template render them as [here](https://v4-alpha.getbootstrap.com/components/navs/#fill-and-justify)

Optional:
- [ ] rate the page
- [ ] arrow to `choose your topic` (not needed)

**Comment by hnykda** [comment]
![image](https://user-images.githubusercontent.com/2741256/34407762-6f8865e4-ebc0-11e7-8a77-e79d7541b5b8.png)

![image](https://user-images.githubusercontent.com/2741256/34407764-7496e9f2-ebc0-11e7-8790-a150d0476135.png)

**Comment by DavidJanku** [comment]
this version seems to me like the single articles (social impact, career, academia) are parts of the same one document. I think it would be better to present it as distinct strategies for crafting one´s thesis, as it is closer to reality. Could you make it look more distinct, e.g. as buttons? Also, the functionality should be the same as we have it now with choosing one´s study discipline - there is no default option chosen in the beginning and relevant text only appears after the user clicks on one of the three options. Therefore headline question "What do you want to optimise for with your thesis" is particularly important to be there.

Also, if you can, please add "rate the page" and "arrow to choose your topic" so we can imagine better how it actually looks like and thus design link to 80k hours in the "careers option" accordingly

**Comment by hnykda** [comment]
Sounds reasonable, I will. 

What the rate the page would do? Is it entirely new functionality, so it would be somehow visible in the admin? It's definitely non-trivial functionality, have no idea how to add it now. Would prefer to postpone implementing this to a second milestone.

**Comment by hnykda** [comment]
Yeah, that's why I asked and disagree. Why do you want to tell our users how others rated the particular page or how many people actually voted? It should be an internal information, right?

**Comment by hnykda** [comment]
# Functionality
1. add button to choose your topics (editable in admin)

# Content
is already in admin

**Comment by hnykda** [comment]
done
