### ISSUE TITLE
Topic search

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#55]
New search page as proposed in the redesign
![image](https://user-images.githubusercontent.com/2741256/36078861-606ce14a-0f7c-11e8-9d06-336709fcd8dd.png)

https://cacoo.com/diagrams/t0dRXcF8boiE4Hug#E0D7F

This should be implemented as well https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/79

**Comment by hnykda** [comment]
So IMO best solution would be:

1. let the user first select a discipline from a dropdown menu (select2?)
2. on selection, page will refresh with topics *only* from the selected study discipline
3. relevant (i.e. existing in the current selection) tags will be displayed as in the old version

**Comment by hnykda** [comment]
so done in  07db098

### first, select discipline
![image](https://user-images.githubusercontent.com/2741256/34410584-9d59042c-ebd1-11e7-85cb-ae6ad8e16289.png)

### after the selection, relevant labels shows up
![image](https://user-images.githubusercontent.com/2741256/34410588-a5cb8922-ebd1-11e7-8d44-fdb21aa40e37.png)

### then it works as before
![image](https://user-images.githubusercontent.com/2741256/34410595-b1de54ba-ebd1-11e7-991d-10c91389fe10.png)

**Comment by DavidJanku** [comment]
ok, the structure makes sense, the only thing I´m afraid of is that it could seem patchy to users since one filter is pull-down and the other is tags. However, I´ll discuss it with some designers, my opinion in this is not very strong.

Have you also drawn up how new topics boxes would look like? it would be good to make it like this https://drive.google.com/open?id=1ZYQ5tickPA3BfJx6-Gk5jKdraN0DIMNm

**Comment by hnykda** [comment]
I would say it is not that alien structure - when you e.g. buy stuff online, you also select a category first and then you can set up various "tag"-like attributes. The proposed idea of having two dropdowns is actually even easier to implement, so we can fallback to it, but I personally think it is going against the UX. 

I haven't touch the view of the topics, it is IMO something that someone else (or me, sigh) could do later (it's a front end thingie, not a backend).

**Comment by DavidJanku** [comment]
Filters: since “study discipline” and “area of interest” have both over 10 cathegories, it would be better to have both filters in tags. The result of search will be AND function, showing only topic which falls into stud discipline cathegory and at the same time into into area of interest. Available topics should show after the user fill in BOTH filters.

**Comment by hnykda** [comment]
After discussion with David:

1. display dropdown as labels
2. display topics as cards

url params in search will be implemented later

**Comment by hnykda** [comment]
@mai0elkady Let me summarize what I would like to achieve and let's see how far you can get:

1. instead of dropdown, study disciplines should be listed in the same way as `tags` are right now, but the user can select only a single discipline. When the user hit the page for the first time, only discipline selection should be available. 
2. When they select a discipline, the server send a `GET` request with `?discipline={selected_discipline}`, so e.g. `discipline=maths`. So instead of `POST` [here](https://github.com/ea-czech-republic/efektivnialtruismus.cz/blob/f11e34adf5c7febe6ee43448bdaabaea225ef08a/website/theses/models.py#L97), there should be, in almost very same way, GET used (something like [this](https://chriskief.com/2012/12/16/checking-if-a-get-variable-exists-in-django/)). If no valid argument in `discipline` is sent (or the parametr is not there at all - the first access), the base theses page is rendered as it is now (the previous bullet point). Why using `POST` is wrong is [here](https://docs.djangoproject.com/en/2.0/topics/forms/#get-and-post) (we are not manipulating server state -> get should be used). The method must be also changed in [the template](https://github.com/ea-czech-republic/efektivnialtruismus.cz/blob/f11e34adf5c7febe6ee43448bdaabaea225ef08a/website/theses/templates/theses/thesis_search.html#L18), maybe just changing `method='GET'` would be enough?
3. then, the behavior is same and doesn't have to be changed for now. Just return relevant topics and their tags for the selection. The "blink" will be solved by frontend designers, similarly to display topics as cards.

**Comment by hnykda** [comment]
So it was actually easier than I thought. It doesn't look nice yet, but all the info should be there. @mai0elkady you may take a look at the solution (which is not really nice from JS perspective).

**Comment by hnykda** [comment]
I am closing this right now in favor of https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/58
