### ISSUE TITLE
Adding page rating

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#57]
E.g. having rating stars bar on each page with `How was this site useful`.

https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/54#issuecomment-354497880

**Comment by hnykda** [comment]
Some discussion https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/54#issuecomment-354549890

**Comment by DavidJanku** [comment]
the main goal is certainly for us to know how useful it is for users. However, I think that there is not a strong argument for not showing it to users as well. If the rating will be positive, users will see that the other people think the website has value which can boost their motivation and their own opinion about th e website. There is also a chance that when the rating will be low it would harm visitors experience, but if that is the case, we can hide the rating (and start working on improvements of content). 
Also, when users see that other people already voted, they might be more prone to vote themselves, which could bring us more feecback.

**Comment by hnykda** [comment]
The argument is that it is a sensitive information bringing a little value to the user and it's very unusual behavior (which is something you *have* to consider when designing the website). Could you find any site which has it like this? My first try was [google docs](https://cloud.google.com/compute/docs/quickstarts) where it is as I proposed.

**Comment by DavidJanku** [comment]
after discussions with the UX designers I found out that 1) it would be better to not make it public until we have enough positive responses 2) question is whether people will be using it - one UX designer think they won´t 
----let´s leave it open for this time but a low priority
