### ISSUE TITLE
Topics layout in 3 columns

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#58]
Display light-weight topics as cards in 3 columns 

### Notes 
https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/55#issuecomment-354496516

**Comment by DavidJanku** [comment]
Topics would involve only the headline and as much description as possible. If it would be only incomplete first sentence it doesn't matter. There is no need for tags, sources or "Why it is important" part. The design comes from the idea that most users basically read the headline and skip if they´re not interested, so we want to place as many headlines on the first page as possible, but stick with "card" looking view of topics - therefore 2x3 topics on the first page

**Comment by hnykda** [comment]
Hey David. 

The reason is the fact that you have to run `python manage.py migrate` when you switch to that branch. And then, you'll have to create new study disciplines in the admin (e.g. math and compsci as I did on beta) and then assign them to any of the thesis - then it will show up.

**Comment by hnykda** [comment]
Related https://github.com/ea-czech-republic/efektivnialtruismus.cz/issues/49

**Comment by hnykda** [comment]
https://github.com/ea-czech-republic/efektivnialtruismus.cz/pull/88

**Comment by DavidJanku** [comment]
Hi,

thanks for progress on this one! We´re almost there, however, there are still some things that need fixing:
1) boxes seem to have different length in each row --- ideal length is Title + 9 rows of description
2) some text is overrunning boxes
3) Even for shorter titles, there should be 2 rows of space
4) space between boxes doesn't have to be so wide

![image](https://user-images.githubusercontent.com/31438579/37004157-73fb620c-20c7-11e8-804e-07c40f51180b.png)

![image](https://user-images.githubusercontent.com/31438579/37004194-8a5f054e-20c7-11e8-8634-b440d0539129.png)

Let's give it the last push!

**Comment by hnykda** [comment]
Hey. Thanks for the feedback.

1. any hardcoded size will be hard to sustain on different responsive sizes, such as mobiles, afraid of the 3rd as well
2. The overrunning text is IMO because of hardcoded links - they shouldn't be pasted there as full URL link, but rather as a hypertext link. So instead of http://www.google.com something like [google](http://www.google.com). This is not the problem of the code itself, but rather the content. 

But @Daver2910 do you have an idea how to improve this?

**Comment by Daver2910** [comment]
Tonight I will begin making the website mobile ready, this will mean catching all overrun text like this. It shold be fixed by the end of the week

**Comment by DavidJanku** [comment]
Thanks @Daver2910 ! 
Regarding @hnykda notes 
1) this is a good point, but still, there should be some consistency in how big the boxes are - not necessarily across all devices (PC, tablet mobile), it could be different for each specific device but should be consistent across one device used.   
2) Thanks for noticing, I´ll send it to content builders so they know.

**Comment by DavidJanku** [comment]
Also, one more point - after discussion with UX designer, we found that
- [ ] there should be more space above and under each headline in the topic box
- [ ] ideal length of text in the topic box displayed on PC is 7 rows
- [ ] widen the spacing of the text in the topic box a bit so it looks more airy and less like a wall of text

**Comment by hnykda** [comment]
@DavidJanku I tried to incorporate it the changes. Let me know if it works now.

**Comment by DavidJanku** [comment]
@hnykda looks much better! There is still some over spilling text 
![image](https://user-images.githubusercontent.com/31438579/37557540-f827ba5a-29fd-11e8-8c14-4596738a3a22.png)

![image](https://user-images.githubusercontent.com/31438579/37557538-ebdc9590-29fd-11e8-9832-b40a7a7e45da.png)

Aside of that, it would be great if there wasn´t such a huge space between some words (same as in the table The list of global issues)

btw, I´ve noticed that in some topics text goes to ... in 6th row and in others in 8th row, why is that? 
e.g. here 
![image](https://user-images.githubusercontent.com/31438579/37557586-9e9cbf84-29fe-11e8-9247-4d428125b0f6.png)

**Comment by hnykda** [comment]
1. the text overflow is the issue I mentioned to you before - if there are explicit links instead of hyperlinks with a meaningful text (which is the right think to do - not just a raw link), we cannot do much about it. Change the links from e.g. https://calendar.google.com to [google calendar](https://calendar.google.com).

2. the huge text gaps is because you haven't refreshed the page with CTRL+R.

3. That is because you can see that the content is done as a raw text in one case (the top left topic), while the others are in bullet points. There is no way we could render both reasonably. The only solution is to use one o fit (I would encourage to use simple text rather than bullet points here).

**Comment by DavidJanku** [comment]
1. ok, I´ll check which topics do it and change it in admin.

2. ok, I see that now its working, thanks!

3. ok, I get the difference between bullet points and simple text, but why even within these categories the length of displayed text differs? e.g. topics "Developing metrics of happiness" and "Multi-micronutrient salt fortification...." in the previous screenshot as well as in the this new one below or topics "Psychological welfare of wild animals" (7 rows) and "Humanity´s impact on wild animal suffering" next to it (9 rows)?
Also, this new version looks even more "stuffed" than in the previous screenshot. One of the points UX designer emphasized was making it more"airy" and not like a wall of text by widening the spacing of the text in the topic box and allowing for some space on the edges. I´d align the text in the boxes with topic titles so there is some space on the edges and maybe increase the spacing between rows?   
![image](https://user-images.githubusercontent.com/31438579/37560693-ffd835e0-2a34-11e8-9f7d-d955dc2e5e4e.png)

**Comment by hnykda** [comment]
3. This is my bad in explaining how it works. There is no way to say to do browser "this should be 7 rows" - how do you imagine it would work when we need to support different font sizes on different devices? So the only think we can do is to limit number of words. Currently, it's set to ~30 words, which on the "average" size corresponds roughly to 6-7 rows. 
And please refresh the site with CTRL+R... This is how it looks:
![image](https://user-images.githubusercontent.com/2741256/37563677-86111b08-2a86-11e8-82fb-e99a332aaccc.png)

**Comment by DavidJanku** [comment]
oh yeah, that was my implicit theory on how it works. Let´s leave it to 30 words then ;)

The only thing I´d change now is to align the text in the boxes with topic titles so there is some space on the edges - I´ll show it in the picture below so it´s more obvious. This is where the plain text in the bottom topic should start 
![topics1](https://user-images.githubusercontent.com/31438579/37565498-685563e6-2aa2-11e8-9cd9-fb691e086868.jpg)
this is how we had it before -plain text started aligned with title, but bullet points were shifted to the right - if it would be possible to do it like that but shift the bullet point to the left it would be great - if the bullet points can't be shifted to the left then I´d leave them on the right
![topics2](https://user-images.githubusercontent.com/31438579/37565522-c7fc29ec-2aa2-11e8-9f0b-4e8ac9bb6882.jpg)
  
- the purpose of these boxes is not to convey information but to attract user to click on the title and read the whole topic on topic profile page - therefore I consider "stuffed outlook" as a bigger issue than "less information conveyed

**Comment by hnykda** [comment]
So is this sufficient?
![image](https://user-images.githubusercontent.com/2741256/37567677-92a72116-2aca-11e8-8c3d-83ac8fbf3d8c.png)

Or did I miss something?
