### ISSUE TITLE
Topics should be under `/theses/<topic-slug>` than root `/<topic-slug>`

### ISSUE THREAD

**Issue by hnykda** [ea-czech-republic/efektivnialtruismus.cz#72]
Currently, an url for a thesis topic looks like e.g. `http://effectivethesis.com/compassion-other-humans-and-nonhumans/`. It should be `http://effectivethesis.com/theses/compassion-other-humans-and-nonhumans/`, so it is easier to use it in analytics.

Wagtail builds URLs based on the tree structure under which the pages are created in the admin interface. So if we have Homepage -> Blog -> blog_post_1, blog post will have address `/blog/blog_post_1`. 

Unfortunately, we started to add thesis in the root and then used this https://github.com/ea-czech-republic/efektivnialtruismus.cz/blob/master/website/theses/models.py#L44 to get all children. 

I am not sure about the solution. Is it possible to somehow change the parent page type in wagtail admin? Or do we have to migrate it on a database level? Are there any methods on top of the page (I noticed something like `add_root`)? 

### Wrong solution bellow - ignore it
Just keeping it for a reference...

1. move the current functionality of `ThesisSearch` into `ThesisIndexPage` (that means copying templates and maybe some parts of models.py ThesisSeach definition into ThesisIndexPage)
2. Get rid of `ThesisSearch` and add a new page `ThesisLandingPage` (or something) instead of the old `ThesisIndexPage`. 

This ThesisLandingPage would be the index of the site, while the `ThesisIndexPage` would be still a parent page of ThesisPage. 

By this, we wouldn't have to migrate all 100+ topics, but probably only those few (Propose, Contact, Donate) and we also wouldn't have to rename models (which is always a scary operation). We would only need to change URL in Wagtail Admin for ThesisIndexPage, automatically prepending every topic

^^^ This wouldn't work because ThesisIndexPage still wouldn't be a parent of a ThesisLandingPage...

**Comment by DavidJanku** [comment]
btw I´m not sure that put it like "http://effectivethesis.com/**theses**/compassion-other-humans-and-nonhuman" is a good idea, because "http://effectivethesis.com/**theses**/" is the page, so it could make some problems with data collection. I think the best would be e.g. http://effectivethesis.com/**topics**/compassion-other-humans-and-nonhuman" as this would distinguish it totally from filters page

**Comment by hnykda** [comment]
`/theses/{topic}` is the correct place for it according to any serious standard (such as REST).

**Comment by hnykda** [comment]
@mai0elkady The solution proposed by me is not working, thanks for pointing it out. I just found out that there is a `move` option in the wagtail admin, so apparently it is possible to move a page to another parent page of the same type. That could help us a bit. I am not sure how, but together with the above we it should be plausible.
