### ISSUE TITLE
English website

### ISSUE THREAD

**Issue by nadvornix** [ea-czech-republic/efektivnialtruismus.cz#73]
It would be useful to have an english version of our website with same design as efektivni-altruismus.cz, but somewhat different content: our strategy, description of EA theses and other projects... [Here is description of i18n in wagtail that could be useful](http://docs.wagtail.io/en/latest/advanced_topics/i18n/). Writing content of this webpage is not part of this issue.

**Comment by DavidJanku** [comment]
That´s actually good point! If we leave out the content, it may not be so time consuming
