### ISSUE TITLE
information from coversion 

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#74]
It would be very valuable to have all available information about people who convert - fill in and send us application form for a topic. This information comes from their URL/IP address, right? What kind of info do we collect (which country are they from, pc/mobile/tablet....)?

**Comment by hnykda** [comment]
I don't know how to embed any data into conversion and haven't found any in the docs nor on the net. https://support.google.com/adwords/answer/6095821?co=ADWORDS.IsAWNCustomer%3Dtrue&oco=0 . Could we ask someone?

**Comment by DavidJanku** [comment]
ok, so I´ve asked Mack and he said there should be some code to extract from Analytics which will send all these data to Analytics (which is basically what we need). I´ve made a search and this is what I found.
The thing we´re looking for is "how to set up event tracking in analytics" - [this](https://youtu.be/IqDEuTLVraA) is a general video by google: https://youtu.be/IqDEuTLVraA. According to [this video](https://youtu.be/iaJ9HHvKeL8) (https://youtu.be/iaJ9HHvKeL8), we have to install Google Tag Manager. I think theoretically you could do it somehow else yourself without the google tag manager, but with the google tag manager, I´ll be able to do it too which will save you time. Also, I believe in the future there will be more tags needed and this could be pretty helpful.
How to do it is here: 
![image](https://user-images.githubusercontent.com/31438579/35103753-bc4fde3a-fc5e-11e7-975c-a7ece5e9070c.png)

Copy the code below and paste it onto every page of your website.

Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MXM5KZ9');</script>


Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MXM5KZ9"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>


Are you ok with installing google tag manager or should I look for some other way how to generate the specific code we need?

Also, would you please explain me how the conversions for google adwords work? Is it that submitting the form directs user through some blank page with the tracking code and then to the page where there is a possibility to share the topic?

**Comment by DavidJanku** [comment]
Also, you can possibly set up Google tag manager right from analytics 
![image](https://user-images.githubusercontent.com/31438579/35113489-7b110640-fc79-11e7-92b3-762f1ec39a6c.png)

**Comment by hnykda** [comment]
I don't really understand how the tag manager works, but I added the `gtag.js` global site tag from the google analytics. Is it enough, or should I also add the one from the first post?

**Comment by hnykda** [comment]
solved
