### ISSUE TITLE
Embedding FB share dialog

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#77]
I think the right spelling is "Share this great news WITH your friends on facebook"

![image](https://user-images.githubusercontent.com/31438579/35005864-cfe18d7c-faec-11e7-8436-a26042b70fcf.png)

Also, would it be possible to this window directly to page Thank you page, so the user doesn't have to click on the link and then click again for sharing but can share directly? 

![image](https://user-images.githubusercontent.com/31438579/35005977-3055cf4c-faed-11e7-9144-e090dfb08e12.png)

**Comment by hnykda** [comment]
That spelling mistake is in beta.

**Comment by brandnk** [comment]
I am not sure if I am 100% accurate, but from my research it does not appear that embedding the facebook share dialog into the body of the page is possible for security reasons and only opening the share dialog in a popup/new window is allowed. It is possible for a popup window to appear on the same page as the share button, though.

I advocate implementing a solution with the FB Javascript SDK to create a share button:

![image](https://user-images.githubusercontent.com/25831028/36702485-4b35276a-1b25-11e8-87c4-ac7988a1be5f.png)

**Comment by hnykda** [comment]
Solved in #89
