### ISSUE TITLE
URL of specific study disciplines

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#79]
For Adwords (which creates 90 % of our traffic), it would help to target people to URL containing all topics from specific study discipline, e.g. "research topics in psychology", "research topics in history". Currently, we don´t have anything like that. Would it be able to project the choice that users make via tags to the URL address?

e.g. I come to http://effectivethesis.com/theses/, click on tag "psychology" and the URL address changes to http://effectivethesis.com/theses/#psychology (or something like that) but the page remains the same as before. Would it be possible?
If not, is there an easy solution how to restructure the website in order to get URL addresses gathering all topics from one study discipline (http://effectivethesis.com/theses/psychology; http://effectivethesis.com/theses/economics, etc...)? 

If the solution would be considerably difficult, I´ll consult the potential benefits of this kind of targeting with the Brainslab (org which manages our account) to estimate whether it is worth it or not.   

EDIT: Also, we had a suggestion coming via feedback button that it would be useful to add a "save button" to make a shortlist of theses before contacting the sponsoring orgs.

**Comment by hnykda** [comment]
this is definitely possible, probably using GET parameters, so the url would like something like `/theses?disciplines=psychology,maths`

**Comment by hnykda** [comment]
Solved by https://github.com/ea-czech-republic/efektivnialtruismus.cz/pull/83
