### ISSUE TITLE
Remove feedback button

### ISSUE THREAD

**Issue by Daver2910** [ea-czech-republic/efektivnialtruismus.cz#85]
Feedback button on each page is not useful.
David Janku agreed to remove it.

Button '#1' below

![et](https://user-images.githubusercontent.com/31806168/36425888-a25610ea-1648-11e8-8fb5-f57c8c8b2e57.PNG)

**Comment by hnykda** [comment]
https://github.com/ea-czech-republic/efektivnialtruismus.cz/pull/88
