### ISSUE TITLE
Front-end features in Highest social impact article

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#86]
- [x] Edit the table - give it more bordelines co it looks like a real table (or copy part of the CSS code from https://80000hours.org/articles/cause-selection/ - this is the page we took the table from)
- [x] Edit the table - align hypertext links to the left in order to remove huge gaps between words
- [x] Edit pictures in this article - make them responsive - when displaying on PC screen they should be bigger and more connected with text, when on mobile or tablet they should be in one column with text, not overhanging as it is now

**Comment by brandnk** [comment]
I believe I accomplished the first point by editing the table directly in the wagtail CMS at http://beta.effectivethesis.com/how-choose-thesis/. I just just wondering though...does the table appear in any of the repository files or is it only generated by wagtail?

**Comment by hnykda** [comment]
@DavidJanku : 

1. borders added
2. the text is aligned to the left in the table right now
3. they are responsive right now. "more connected with text" probably means to much of white space between the paragraph text and the image. But this is caused by the fact that the pictues have big white space inside them. Hence, they must be cropped and then it would look fine. Can you do it yourself @DavidJanku ?

**Comment by DavidJanku** [comment]
Thanks for this!
1. it could be even more salient - e.g. we can copy the style of the table they use here https://80000hours.org/articles/cause-selection/  since we´re going to cite this table anyway
2.  It would be great if there weren´t strange spaces between words like in "Promoting effective altruism" or "Risks from Artificial intelligence"
![image](https://user-images.githubusercontent.com/31438579/37556956-506c509e-29f5-11e8-8cf6-a736ab67fc64.png)
3. I´ll try

**Comment by hnykda** [comment]
@DavidJanku please refresh the site with `CTRL+R` - your browser is caching it.

**Comment by DavidJanku** [comment]
1. ok, if it´s not that easy then we can leave it as it is. I thought it would look better if the first row was grey and the outside borders were thicker same as they have in their table, but it might be only my perception, not UX feature, so no need to invest much time into it if its not easy.
2. my bad, thanks! works well!

**Comment by brandnk** [comment]
1. If you want the table to be changed, I think can have that arranged. By the way, are we using the most current version of bootstrap (4.x)? I think we are still on v4 alpha 6 (previous version) so I am not able to add the classes that I want to.

**Comment by hnykda** [comment]
@brandnk I updated it here on a redesign branch to use v4 (when I started with this, alpha 7 was the newest one). And I added `thead-light` to that table.

@DavidJanku If it's only about having the grey header, here is the new version:
![image](https://user-images.githubusercontent.com/2741256/37560108-b5b4982a-2a32-11e8-84d4-c94b07c2da8d.png)

**Comment by DavidJanku** [comment]
cool, let´s consider it done! thanks a lot! :)
