### ISSUE TITLE
Front-end features in Improving career prospects article

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#87]
- [x] buttons highest social impact a reseach career in academia in the end of the article align to the center and make a bit smaller
- [x] connect these buttons with specific articles - now they only direct users to the main menu and users have to click again to choose an article - instead, these buttons should direct users directly to the expected article
- [x] the very last part of the article (Don you want more career advice? and the image) align to the center

**Comment by Daver2910** [comment]
http://beta.effectivethesis.com/how-choose-thesis/

To confirm, these buttons? at this url?

![123](https://user-images.githubusercontent.com/31806168/36479374-c416de56-1708-11e8-9d54-0a55e5828c46.PNG)

**Comment by DavidJanku** [comment]
Yes, exactly

**Comment by hnykda** [comment]
1. Done
2. Done
3. I propose to replace it just by `Then visit 80000hours.org!` (with clickable link and redirect). Having just a picture there is IMO confusing (considering the fact that the user doesn't know what 80000Hours is). Is it all right?

**Comment by DavidJanku** [comment]
Thanks!
1. Buttons appear to me like this:
![image](https://user-images.githubusercontent.com/31438579/37556983-b87bcee4-29f5-11e8-8d0a-47d8341083ab.png) - can we make a bigger space between them?
2. Awesome, thanks!
3. yeah that´s good idea we agreed on with the UX designer as well. I forgot to update it. However, it would still be good to make it more salient. UX designer suggested putting there text explaining what 80k hours is and some picture or their logo underneath. something like "Visit 80,000 hours, organisation providing evidence-based career advice on how to find fulfilling, high-impact career!"

**Comment by hnykda** [comment]
1. Yeah, added:
![image](https://user-images.githubusercontent.com/2741256/37557199-6c5a4836-2a01-11e8-9f37-5639755b6e82.png)
3. Then I encourage you to do so in admin. Upload the size of the logo to use it in text.

**Comment by DavidJanku** [comment]
1. Maybe a bit more? Twice as much as now (if it wont look too weird then)?

2. I´ve edited it, but centering the picture would still be good

**Comment by hnykda** [comment]
1. 
![image](https://user-images.githubusercontent.com/2741256/37560129-385b45da-2a33-11e8-861e-fc1e31951f23.png)
2. 
![image](https://user-images.githubusercontent.com/2741256/37560153-a40af5c8-2a33-11e8-97ff-6ba99b8c0074.png)

**Comment by DavidJanku** [comment]
1. would it be possible to align buttons to the center? it doesn't look that good when they are shifted towards left side. Also, are they darker then they used to be? If it doesn't have some important reason, I´d keep them brighter 

2. works great, thanks!

**Comment by hnykda** [comment]
1. Done. The colors are updated based on recommendation from the [Boostrap 4 buttons](https://getbootstrap.com/docs/4.0/components/buttons/) - one of the most [popular package](https://github.com/twbs/bootstrap) on github and influenced by gazilion of designers and FE devs, so if you don't have a strong argument against, I would stick to their recommendation (colors are chosen in a way that they works on most platforms, for color blind and so on).

**Comment by DavidJanku** [comment]
ok, makes sense, thanks!
