### ISSUE TITLE
Frontend tweaks

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#94]
Landing page:
- [ ] widen spacing between rows of text a little bit so it looks more airy

How choose thesis page (http://beta.effectivethesis.com/how-choose-thesis/)
- [ ] spread buttons over the entire width (not aligning them to left)
- [x] add more contrast to selected button - now it's not that obvious which button is selected 
- [ ] distinguish headline of individual articles (Highest social impact; Improving career prospect, Research career (in academia)) from other headlines - make it even bigger or somehow different from all other headlines - now the difference is not emphasized enough

Filters page (http://beta.effectivethesis.com/theses/)
- [x] make tags bigger - now they´re too small and hard to read
- [x] edit the system so admin doesn't have to put this symbol _ into 2 words tag (e.g. political_science; communication_media_marketing)

**Comment by hnykda** [comment]
Landing page: Where exactly? There are like 3 different types of text. Very top? The text below? Process?

How to choose page:
1. I don't agree, it looks terrible when clicking on some button and selecting text. I could center everything to the center, but that is very weird as well. Or do you really want this?
![image](https://user-images.githubusercontent.com/2741256/37556927-45ab4ebe-29fd-11e8-940c-d5c8c34380a1.png)
2. Done (hope it's enough)
3. This can be done in the admin. They are already H2, so I suggest putting the rest as H3.

Filters page:
1. done - font 14px instead 12px
2. `study discipline` in snippets in admin doesn't need to have `_` - I don't know why you guys create it in this way (see `test me` on the image below). In `tags` they are already replaced by spaces:
![image](https://user-images.githubusercontent.com/2741256/37556994-4ae5a2ca-29fe-11e8-8dec-5d286de4adb6.png). Hence, admin change.

**Comment by DavidJanku** [comment]
Landing page:
1. Text that says "You will likely invest hundreds of hours and huge effort in your final thesis. What about using this opportunity for something more than just “have it done”? We can help you have high social impact with your thesis, improve your career prospects or prepare for research career in academia."

Choose thesis page:
1. would it be possible to spread these buttons so the "highest social impact" is aligned totally left so it starts with the same column as titles (What you want to optimise and Improving career prospects). Or would it be too much?
2. thanks, looks good!
3. I´ve tried to make it smaller as you suggested, but it doesn't look very good. The options would be to make it even bigger or distinguish it in some other dimension than size. I don't have an idea what this dimension would be - color? or make it underlined? Do you have any idea what to do about it?

Filters page
1. Text is bigger, but have tags got bigger as well? I might try to make tags even a bit bigger than they are now.
2. when I was tagging all topic in beta it didn't work with space, it had to be all text or there was a bug message. It´s doing the same thing now when I click on some two words tag

**Comment by hnykda** [comment]
Landing page:
1. done. Anything bigger than this will look weird on mobile devices.

Choose page:
1. it would, but looks weird (the reason for the little margin on the left is that it is clear that buttons correspondents to the header). Will leave the decision to you.
![image](https://user-images.githubusercontent.com/2741256/37560274-8bfde8b2-2a35-11e8-9826-c192fca9dcf0.png)
3. This is on a very top and only a single header. I fail to understand what UX it brings making it even bigger/popping. I think it's clear that it is a header - it's the very first thing with the biggest and the boldest  font on the page. If we want that to stand it out, we can make the corresponding headers smaller. There is a very good reason why we want to keep any extra styling low.

**Comment by DavidJanku** [comment]
Landing page 
1. ok, thanks!

Choose page
1. Originally, I meant something like this
![buttons](https://user-images.githubusercontent.com/31438579/37560808-1f247a60-2a37-11e8-8857-bb2328ee2d74.png)
which looks bad, so I propose something like this 
![buttons2](https://user-images.githubusercontent.com/31438579/37560810-2f4a9640-2a37-11e8-87ba-fef1a76169d1.jpg)
I´m not sure how much is this UX feature and how much just graphics feature, however, it was raised by the UX guy during our interview

3. I guess the UX guy didnt like that element "What do you want to optimize your thesis for?" is same as element "Article title (e.g. Highest Social impact)". I don't think making element "What do you want to optimize your thesis for?" smaller would look good, so let´s just leave it as it is and I will ask him for better explanation why it is important to distinguish it.

Filters

1. ok, looks good! Thanks!
2. tags for Pick area of interest works well, but look what it shows me when I click on "agricultural science" (or any two words tag) in Pick your study discipline. Does it work for you properly?
![image](https://user-images.githubusercontent.com/31438579/37560895-9623917c-2a38-11e8-8e06-aebb93c2e175.png)

**Comment by hnykda** [comment]
Choose page:
1. OK, done:
![image](https://user-images.githubusercontent.com/2741256/37564090-1909a65c-2a8f-11e8-97e1-f87d11248596.png)

2. Ah, now I got it. So would this work?
![image](https://user-images.githubusercontent.com/2741256/37563864-3b766fcc-2a8a-11e8-8e70-6ba2c28b488d.png)

Filters:
2. Fixed, thanks, that was a bug.

**Comment by DavidJanku** [comment]
Choose topic
1. looks much better, thanks!
2. you made the "What do you want to optimize your thesis for?" even bigger? :D Yeah, I guess now it fulfills the UX function. Just one detail - I would change this sentence to "What do you want to focus on with your thesis?" - I didn't find how to edit it in admin.

**Comment by hnykda** [comment]
Choose topic:

2. Yeah, making this bigger is IMO still fine, since it is not part of the text below. As I wrote, I originally thought that you mean making the headers below bigger, which had the issues I wrote above.
