### ISSUE TITLE
Summary borders

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#96]
now the Summary section is set into the table which doesn't look as good and also there is too much space above and under the text. It would be good if it looked like this "The bottom line" part 
![image](https://user-images.githubusercontent.com/31438579/37557441-a341ee9e-29fc-11e8-9dba-dc458922ae09.png)

We might copy the style from this page https://80000hours.org/career-guide/high-impact-jobs/

Alternatively, we can just dele the free space above and under the text and make the borders more salient (thicker)

**Comment by brandnk** [comment]
Which page of the website is this problem occurring?

**Comment by DavidJanku** [comment]
on this one http://beta.effectivethesis.com/how-choose-thesis/ in all 3 articles: http://beta.effectivethesis.com/how-choose-thesis/#impact; http://beta.effectivethesis.com/how-choose-thesis/#career and http://beta.effectivethesis.com/how-choose-thesis/#research

**Comment by brandnk** [comment]
I just published a change in the wagtail admin area. Added `.mt-1` class to `<h4>` containing "Summary" text and `.mt-3` class to parent `<table>` element :

**BEFORE:**
![image](https://user-images.githubusercontent.com/25831028/37561659-89559bf6-2a2a-11e8-86ed-20f9aa1eb6a7.png)

**AFTER:**
![image](https://user-images.githubusercontent.com/25831028/37561690-52e21f3a-2a2b-11e8-8a50-a2c127e302b2.png)

**Comment by DavidJanku** [comment]
@brandnk ok, looks better, thanks!

**Comment by DavidJanku** [comment]
@brandnk Hi Brandon, would you please take a look at this? We dont need the second empty cell there
![image](https://user-images.githubusercontent.com/31438579/37655436-9684fb38-2c45-11e8-9e39-905922c70dfc.png)

**Comment by brandnk** [comment]
Sorry, didn't know the original problem persisted for all three of the focus choices. I applied the same fix to the "Improving career prospects" section and for the "Research career in academia" section the Summary box will now on larger screens not take the entire width of the container and be centered in the middle. Let me know if this helps.

**AFTER:**
![image](https://user-images.githubusercontent.com/25831028/37690359-c7895cd4-2c80-11e8-903e-e5a406731f04.png)
