### ISSUE TITLE
collecting emails from users

### ISSUE THREAD

**Issue by DavidJanku** [ea-czech-republic/efektivnialtruismus.cz#97]
I haven't found a way how to implement google forms into the article. Would you please do it?
Its in the article Improving career prospects
![image](https://user-images.githubusercontent.com/31438579/37559798-f21bbf96-2a23-11e8-828d-aca10b577856.png)

**Comment by hnykda** [comment]
This is maximum you can do with google forms:
![image](https://user-images.githubusercontent.com/2741256/37567823-7cdb6a7a-2acc-11e8-8c69-c746d3f85085.png)

**Comment by DavidJanku** [comment]
ok, let´s do mailchimp. i dont insist on google forms ;)
